// ==================== ゲーム状態 ====================
let state = {
  mode: 'solo',
  playerId: null,
  playerName: '',
  countryKey: null,
  year: '01',
  challenge: 'free',
  challengeStatus: 'pending',
  isTurnProcessing: false,
  turn: 0,
  turnLimit: TURN_COUNT,
  budget: 0,
  initialBudget: 0,
  finalScore: 0,
  totalFoodValue: 0,
  envScore: 70,
  techPoints: 0,
  eraIndex: 0,
  customPreset: null,
  chartData: [],
  initialAvgNdvi: 0,
  resilienceScore: 50,
  climateRisk: 0,
  climatePulse: null,
  baseMapPotential: [],   // 初期NDVI（不変）
  currentMapNdvi: [],     // 現在NDVI（更新）
  avgNdvi: 0,
  soilMoisture: 0,
  precipitation: 0,
  temperature: 0,
  competitionEventId: null,
  competitionEventName: '',
  competitionSeed: null,
  simulationVersion: null,
  randomizer: null,
  history: [],
  unlocked: {},
  skillUsed: false
};
